# Generated by Django 5.0.6 on 2025-01-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_date_created_alter_post_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
